package com.smartretail.pricemonitor.util;

import java.math.BigDecimal;
import java.util.List;

public class CommodityCatalogData {

    public record CommoditySeedItem(
        String categoryName,
        String name,
        String code,
        String unit,
        BigDecimal baseBenchmarkPrice,
        String description
    ) {}

    public static List<CommoditySeedItem> getMasterCatalog() {
        return List.of(
            // ==========================================
            // CATEGORY 1: VEGETABLES (40 Commodities)
            // ==========================================
            item("Vegetables", "Onion (Small / Shallots)", "VEG_ONION_SMALL", "KG", "55.00", "Small red shallot onions sourced from South Indian mandis"),
            item("Vegetables", "Onion (Big / Red)", "VEG_ONION_BIG", "KG", "35.00", "Grade A red onions from Maharashtra and Tamil Nadu APMC mandis"),
            item("Vegetables", "Tomato (Hybrid)", "VEG_TOMATO_HYBRID", "KG", "30.00", "Firm hybrid red tomatoes for retail"),
            item("Vegetables", "Tomato (Local / Country)", "VEG_TOMATO_LOCAL", "KG", "28.00", "Tangy local country tomatoes"),
            item("Vegetables", "Potato (Jyoti / White)", "VEG_POTATO_WHITE", "KG", "25.00", "White Jyoti variety table potatoes"),
            item("Vegetables", "Potato (Pahadi / Red)", "VEG_POTATO_RED", "KG", "32.00", "Mountain hill-grown red skin potatoes"),
            item("Vegetables", "Brinjal (Round / Purple)", "VEG_BRINJAL_PURPLE", "KG", "40.00", "Fresh purple round eggplants"),
            item("Vegetables", "Brinjal (Long / Green)", "VEG_BRINJAL_GREEN", "KG", "35.00", "Long light green country brinjals"),
            item("Vegetables", "Cabbage (Green)", "VEG_CABBAGE_GREEN", "KG", "22.00", "Fresh green head cabbage"),
            item("Vegetables", "Cauliflower", "VEG_CAULIFLOWER", "KG", "38.00", "White compact cauliflower curds"),
            item("Vegetables", "Carrot (Red / Local)", "VEG_CARROT_RED", "KG", "45.00", "Sweet red winter carrots"),
            item("Vegetables", "Carrot (Orange / English)", "VEG_CARROT_ORANGE", "KG", "50.00", "Juicy orange English carrots"),
            item("Vegetables", "Cucumber (Green)", "VEG_CUCUMBER_GREEN", "KG", "25.00", "Fresh green salad cucumbers"),
            item("Vegetables", "Cucumber (Yellow / Dosakai)", "VEG_CUCUMBER_YELLOW", "KG", "22.00", "Traditional yellow cooking cucumber"),
            item("Vegetables", "Drumstick (Moringa)", "VEG_DRUMSTICK", "KG", "70.00", "Fresh green moringa drumsticks"),
            item("Vegetables", "Garlic (Native)", "VEG_GARLIC_NATIVE", "KG", "180.00", "Small pungent native garlic bulbs"),
            item("Vegetables", "Garlic (Ooty Hybrid)", "VEG_GARLIC_HYBRID", "KG", "220.00", "Large clove Ooty white garlic"),
            item("Vegetables", "Ginger (Fresh Green)", "VEG_GINGER_FRESH", "KG", "90.00", "Aromatic fresh green ginger root"),
            item("Vegetables", "Green Chilli (Small Spicy)", "VEG_CHILLI_SPICY", "KG", "60.00", "Pungent small green chillies"),
            item("Vegetables", "Green Chilli (Long Light Green)", "VEG_CHILLI_LONG", "KG", "50.00", "Mild long green peppers"),
            item("Vegetables", "Lady Finger (Okra / Bhindi)", "VEG_LADY_FINGER", "KG", "42.00", "Tender green okra pods"),
            item("Vegetables", "Bitter Gourd (Karela)", "VEG_BITTER_GOURD", "KG", "48.00", "Fresh green bitter gourd"),
            item("Vegetables", "Bottle Gourd (Lauki)", "VEG_BOTTLE_GOURD", "KG", "28.00", "Tender green bottle gourd"),
            item("Vegetables", "Pumpkin (Yellow / Kaddu)", "VEG_PUMPKIN_YELLOW", "KG", "24.00", "Sweet ripe yellow pumpkin"),
            item("Vegetables", "Radish (White / Mooli)", "VEG_RADISH_WHITE", "KG", "30.00", "Crisp white root radish with leaves"),
            item("Vegetables", "Spinach (Palak)", "VEG_SPINACH_PALAK", "KG", "35.00", "Fresh leafy green spinach bunches"),
            item("Vegetables", "Capsicum (Green Shimla Mirch)", "VEG_CAPSICUM_GREEN", "KG", "65.00", "Crisp green bell peppers"),
            item("Vegetables", "Capsicum (Red Bell Pepper)", "VEG_CAPSICUM_RED", "KG", "140.00", "Exotic red bell peppers"),
            item("Vegetables", "Beetroot", "VEG_BEETROOT", "KG", "38.00", "Deep red sweet beetroots"),
            item("Vegetables", "French Beans", "VEG_FRENCH_BEANS", "KG", "55.00", "Tender stringless french green beans"),
            item("Vegetables", "Cluster Beans (Gawar Phali)", "VEG_CLUSTER_BEANS", "KG", "45.00", "Fresh green cluster beans"),
            item("Vegetables", "Green Peas (Fresh Matar)", "VEG_GREEN_PEAS_FRESH", "KG", "75.00", "Sweet green peas in pods"),
            item("Vegetables", "Button Mushroom", "VEG_MUSHROOM_BUTTON", "KG", "160.00", "Fresh white button mushrooms"),
            item("Vegetables", "Colocasia (Arbi / Seppankizhangu)", "VEG_COLOCASIA", "KG", "42.00", "Taro root colocasia tubers"),
            item("Vegetables", "Elephant Foot Yam (Senai)", "VEG_YAM_ELEPHANT", "KG", "50.00", "Firm elephant foot yam root"),
            item("Vegetables", "Ridge Gourd (Turai / Peerkangai)", "VEG_RIDGE_GOURD", "KG", "44.00", "Tender ridged luffa gourd"),
            item("Vegetables", "Snake Gourd (Pudalangai)", "VEG_SNAKE_GOURD", "KG", "36.00", "Long green striped snake gourd"),
            item("Vegetables", "Ash Gourd (Pooshnikai)", "VEG_ASH_GOURD", "KG", "26.00", "Large wax ash gourd"),
            item("Vegetables", "Raw Green Banana (Vazhaikkai)", "VEG_RAW_BANANA", "KG", "30.00", "Green raw cooking bananas"),
            item("Vegetables", "Sweet Potato (Chakkara Valli)", "VEG_SWEET_POTATO", "KG", "38.00", "Pink-skinned sweet potato roots"),

            // ==========================================
            // CATEGORY 2: FRUITS (40 Commodities)
            // ==========================================
            item("Fruits", "Apple (Fuji Imported)", "FRU_APPLE_FUJI", "KG", "180.00", "Crisp sweet Fuji apples"),
            item("Fruits", "Apple (Kashmiri Red Delicious)", "FRU_APPLE_KASHMIRI", "KG", "140.00", "Sweet aromatic Kashmiri red apples"),
            item("Fruits", "Banana (Robusta Yellow)", "FRU_BANANA_ROBUSTA", "KG", "38.00", "Grade A Robusta table bananas"),
            item("Fruits", "Banana (Nendran)", "FRU_BANANA_NENDRAN", "KG", "55.00", "Large Kerala Nendran bananas"),
            item("Fruits", "Banana (Red Banana / Sevvazhai)", "FRU_BANANA_RED", "KG", "80.00", "Nutritious premium red bananas"),
            item("Fruits", "Mango (Alphonso / Hapus)", "FRU_MANGO_ALPHONSO", "KG", "250.00", "Premium Ratnagiri Alphonso mangoes"),
            item("Fruits", "Mango (Totapuri)", "FRU_MANGO_TOTAPURI", "KG", "50.00", "Firm tangy Totapuri mangoes"),
            item("Fruits", "Mango (Banganapalli)", "FRU_MANGO_BANGANAPALLI", "KG", "90.00", "Sweet juicy Andhra Banganapalli mangoes"),
            item("Fruits", "Mango (Dasheri)", "FRU_MANGO_DASHERI", "KG", "80.00", "Aromatic North Indian Dasheri mangoes"),
            item("Fruits", "Orange (Nagpur Mandarins)", "FRU_ORANGE_NAGPUR", "KG", "70.00", "Juicy Nagpur mandarin oranges"),
            item("Fruits", "Papaya (Red Lady)", "FRU_PAPAYA_RED_LADY", "KG", "35.00", "Sweet red flesh papaya"),
            item("Fruits", "Pineapple (Mauritius)", "FRU_PINEAPPLE", "KG", "55.00", "Juicy sweet Mauritius pineapples"),
            item("Fruits", "Pomegranate (Kesar)", "FRU_POMEGRANATE", "KG", "160.00", "Deep red seed Kesar pomegranates"),
            item("Fruits", "Watermelon (Kiran)", "FRU_WATERMELON", "KG", "22.00", "Sweet dark red flesh watermelons"),
            item("Fruits", "Muskmelon (Kharbooja)", "FRU_MUSKMELON", "KG", "35.00", "Aromatic yellow cantaloupe muskmelon"),
            item("Fruits", "Guava (Allahabad Safeda)", "FRU_GUAVA_SAFEDA", "KG", "60.00", "Crisp white flesh Allahabad guavas"),
            item("Fruits", "Grapes (Black Seedless)", "FRU_GRAPES_BLACK", "KG", "110.00", "Sweet black seedless grapes"),
            item("Fruits", "Grapes (Green Thompson)", "FRU_GRAPES_GREEN", "KG", "85.00", "Juicy green Thompson seedless grapes"),
            item("Fruits", "Lemon (Lime / Nimbu)", "FRU_LEMON_NIMBU", "KG", "90.00", "Juicy yellow lemons"),
            item("Fruits", "Tender Coconut (Elaneer)", "FRU_TENDER_COCONUT", "PIECE", "45.00", "Fresh green tender coconut with coconut water"),
            item("Fruits", "Custard Apple (Sitaphal)", "FRU_CUSTARD_APPLE", "KG", "120.00", "Sweet pulp custard apples"),
            item("Fruits", "Jackfruit (Kathal)", "FRU_JACKFRUIT", "KG", "45.00", "Ripe sweet jackfruit bulbs"),
            item("Fruits", "Fig (Fresh Anjeer)", "FRU_FIG_ANJEER", "KG", "180.00", "Fresh purple sweet figs"),
            item("Fruits", "Sapota (Chikoo)", "FRU_SAPOTA_CHIKOO", "KG", "55.00", "Sweet brown chikoo sapota"),
            item("Fruits", "Sweet Lime (Mosambi)", "FRU_MOSAMBI", "KG", "65.00", "Juicy sweet lime mosambi"),
            item("Fruits", "Indian Gooseberry (Amla)", "FRU_AMLA", "KG", "50.00", "Vitamin C rich fresh green amla"),
            item("Fruits", "Strawberry (Mahabaleshwar)", "FRU_STRAWBERRY", "KG", "280.00", "Fresh red Mahabaleshwar strawberries"),
            item("Fruits", "Pear (Green / Nashpati)", "FRU_PEAR_NASHPATI", "KG", "120.00", "Crisp green Indian pears"),
            item("Fruits", "Plum (Red Indian)", "FRU_PLUM_RED", "KG", "150.00", "Sweet red plums"),
            item("Fruits", "Peach (Local)", "FRU_PEACH", "KG", "160.00", "Juicy local pink peaches"),
            item("Fruits", "Dragon Fruit (Red Flesh)", "FRU_DRAGON_FRUIT", "KG", "190.00", "Exotic magenta dragon fruit"),
            item("Fruits", "Kiwi Fruit (Imported)", "FRU_KIWI", "PIECE", "35.00", "Imported green kiwi fruit"),
            item("Fruits", "Avocado (Hass)", "FRU_AVOCADO", "KG", "320.00", "Creamy Hass avocados"),
            item("Fruits", "Dates (Fresh Wet Dates)", "FRU_DATES_FRESH", "KG", "220.00", "Sweet fresh wet dates"),
            item("Fruits", "Litchi (Shahi Litchi)", "FRU_LITCHI", "KG", "180.00", "Juicy Bihar Shahi litchis"),
            item("Fruits", "Wood Apple (Bael)", "FRU_WOOD_APPLE", "KG", "40.00", "Aromatic hard shell wood apple"),
            item("Fruits", "Passion Fruit", "FRU_PASSION_FRUIT", "KG", "140.00", "Tangy purple passion fruit"),
            item("Fruits", "Pink Custard Apple", "FRU_CUSTARD_PINK", "KG", "150.00", "Exotic pink pulp sitaphal"),
            item("Fruits", "Star Fruit (Carambola)", "FRU_STAR_FRUIT", "KG", "80.00", "Crisp star fruit carambola"),
            item("Fruits", "Mangosteen", "FRU_MANGOSTEEN", "KG", "350.00", "Exotic purple mangosteen"),

            // ==========================================
            // CATEGORY 3: CEREALS & GRAINS (40 Commodities)
            // ==========================================
            item("Cereals & Grains", "Rice (Sona Masoori Raw)", "GRA_RICE_SONA_RAW", "KG", "58.00", "Premium Sona Masoori raw rice"),
            item("Cereals & Grains", "Rice (Sona Masoori Boiled)", "GRA_RICE_SONA_BOILED", "KG", "54.00", "Standard Sona Masoori parboiled rice"),
            item("Cereals & Grains", "Rice (Basmati Extra Long)", "GRA_RICE_BASMATI", "KG", "135.00", "Aged extra long grain Basmati rice"),
            item("Cereals & Grains", "Rice (Ponni Raw)", "GRA_RICE_PONNI_RAW", "KG", "62.00", "Tamil Nadu Ponni raw rice"),
            item("Cereals & Grains", "Rice (Ponni Boiled)", "GRA_RICE_PONNI_BOILED", "KG", "56.00", "Tamil Nadu Ponni boiled rice"),
            item("Cereals & Grains", "Rice (Idli Rice Short Grain)", "GRA_RICE_IDLI", "KG", "42.00", "Short fat grain idli rice"),
            item("Cereals & Grains", "Rice (IR64 Parboiled)", "GRA_RICE_IR64", "KG", "38.00", "Government MSP IR64 parboiled rice"),
            item("Cereals & Grains", "Rice (Govind Bhog)", "GRA_RICE_GOVIND_BHOG", "KG", "110.00", "Aromatic Bengal Govind Bhog rice"),
            item("Cereals & Grains", "Wheat (Sharbati Whole)", "GRA_WHEAT_SHARBATI", "KG", "46.00", "MP Sharbati golden wheat grains"),
            item("Cereals & Grains", "Wheat (Lokwan)", "GRA_WHEAT_LOKWAN", "KG", "38.00", "Standard Lokwan mill quality wheat"),
            item("Cereals & Grains", "Wheat Flour (Chakki Atta)", "GRA_WHEAT_ATTA", "KG", "42.00", "100% whole wheat chakki flour"),
            item("Cereals & Grains", "Maida (Refined Flour)", "GRA_MAIDA", "KG", "38.00", "Refined white wheat maida flour"),
            item("Cereals & Grains", "Sooji / Rava (Semolina)", "GRA_SOOJI_RAVA", "KG", "44.00", "Coarse semolina wheat rava"),
            item("Cereals & Grains", "Maize / Yellow Corn", "GRA_MAIZE_CORN", "KG", "26.00", "Dry yellow maize corn grain"),
            item("Cereals & Grains", "Sweet Corn Cob", "GRA_SWEET_CORN", "KG", "35.00", "Fresh sweet corn cobs"),
            item("Cereals & Grains", "Jowar (White Sorghum)", "GRA_JOWAR_WHOLE", "KG", "52.00", "Whole white sorghum millet"),
            item("Cereals & Grains", "Jowar Flour", "GRA_JOWAR_FLOUR", "KG", "58.00", "Pure white jowar millet flour"),
            item("Cereals & Grains", "Bajra (Pearl Millet)", "GRA_BAJRA_WHOLE", "KG", "32.00", "Whole pearl millet bajra"),
            item("Cereals & Grains", "Bajra Flour", "GRA_BAJRA_FLOUR", "KG", "38.00", "Freshly milled bajra flour"),
            item("Cereals & Grains", "Ragi (Finger Millet)", "GRA_RAGI_WHOLE", "KG", "45.00", "Whole finger millet ragi"),
            item("Cereals & Grains", "Ragi Flour", "GRA_RAGI_FLOUR", "KG", "50.00", "Pure finger millet ragi flour"),
            item("Cereals & Grains", "Barley (Jau Whole)", "GRA_BARLEY_JAU", "KG", "40.00", "Whole pearl barley jau grains"),
            item("Cereals & Grains", "Foxtail Millet (Thinai)", "GRA_FOXTAIL_MILLET", "KG", "85.00", "Nutritious foxtail millet grains"),
            item("Cereals & Grains", "Kodo Millet (Varagu)", "GRA_KODO_MILLET", "KG", "90.00", "Fiber-rich kodo millet grains"),
            item("Cereals & Grains", "Little Millet (Samai)", "GRA_LITTLE_MILLET", "KG", "88.00", "Organic little millet samai"),
            item("Cereals & Grains", "Barnyard Millet (Kuthiraivali)", "GRA_BARNYARD_MILLET", "KG", "95.00", "Gluten-free barnyard millet"),
            item("Cereals & Grains", "Proso Millet (Chena)", "GRA_PROSO_MILLET", "KG", "80.00", "Whole proso millet grains"),
            item("Cereals & Grains", "Oats (Rolled Whole)", "GRA_OATS_ROLLED", "KG", "160.00", "Whole rolled breakfast oats"),
            item("Cereals & Grains", "Oats (Instant Flakes)", "GRA_OATS_INSTANT", "KG", "140.00", "Quick cooking instant oats"),
            item("Cereals & Grains", "Paddy (Common Unmilled)", "GRA_PADDY_COMMON", "KG", "23.00", "Govt MSP common paddy rice"),
            item("Cereals & Grains", "Paddy (Grade A)", "GRA_PADDY_GRADE_A", "KG", "25.00", "Govt MSP Grade A paddy rice"),
            item("Cereals & Grains", "Poha (Thick Flattened Rice)", "GRA_POHA_THICK", "KG", "48.00", "Thick flattened rice poha"),
            item("Cereals & Grains", "Poha (Thin Flattened Rice)", "GRA_POHA_THIN", "KG", "52.00", "Paper thin pressed poha"),
            item("Cereals & Grains", "Puffed Rice (Murmura / Pori)", "GRA_PUFFED_RICE", "KG", "60.00", "Crisp puffed rice murmura"),
            item("Cereals & Grains", "Red Rice (Matta Kerala)", "GRA_RICE_MATTA", "KG", "68.00", "Kerala coarse red matta rice"),
            item("Cereals & Grains", "Black Rice (Chak-Hao)", "GRA_RICE_BLACK", "KG", "180.00", "Aromatic Manipur black rice"),
            item("Cereals & Grains", "Buckwheat (Kuttu)", "GRA_BUCKWHEAT", "KG", "120.00", "Fasting buckwheat kuttu flour"),
            item("Cereals & Grains", "Amaranth Grain (Rajgira)", "GRA_AMARANTH", "KG", "130.00", "Whole amaranth rajgira seeds"),
            item("Cereals & Grains", "Wheat Bran", "GRA_WHEAT_BRAN", "KG", "22.00", "High fiber wheat bran flour"),
            item("Cereals & Grains", "Rice Bran", "GRA_RICE_BRAN", "KG", "20.00", "Nutritious rice bran powder"),

            // ==========================================
            // CATEGORY 4: PULSES & LEGUMES (40 Commodities)
            // ==========================================
            item("Pulses & Legumes", "Arhar / Tur Dal (Desi Split)", "PUL_TUR_DAL_DESI", "KG", "150.00", "Traditional split pigeon pea tur dal"),
            item("Pulses & Legumes", "Arhar / Tur Dal (Unpolished)", "PUL_TUR_DAL_UNPOLISHED", "KG", "165.00", "Organic unpolished tur dal"),
            item("Pulses & Legumes", "Moong Dal (Yellow Split)", "PUL_MOONG_YELLOW", "KG", "110.00", "Split yellow moong dal"),
            item("Pulses & Legumes", "Moong Whole (Green Gram)", "PUL_MOONG_WHOLE", "KG", "105.00", "Whole green gram moong"),
            item("Pulses & Legumes", "Moong Dal (Green Chilka)", "PUL_MOONG_CHILKA", "KG", "115.00", "Split green moong with skin"),
            item("Pulses & Legumes", "Urad Dal (White Split)", "PUL_URAD_WHITE_SPLIT", "KG", "130.00", "Skinned split white urad dal"),
            item("Pulses & Legumes", "Urad Dal (White Whole)", "PUL_URAD_WHITE_WHOLE", "KG", "140.00", "Whole skinned white urad dal"),
            item("Pulses & Legumes", "Urad Whole (Black Gram)", "PUL_URAD_BLACK_WHOLE", "KG", "120.00", "Whole black urad gram"),
            item("Pulses & Legumes", "Chana Dal (Split Bengal Gram)", "PUL_CHANA_DAL", "KG", "85.00", "Split Bengal gram chana dal"),
            item("Pulses & Legumes", "Chana Whole (Kala Chana)", "PUL_CHANA_KALA", "KG", "75.00", "Small brown whole chickpea"),
            item("Pulses & Legumes", "Kabuli Chana (White Chickpeas)", "PUL_KABULI_CHANA", "KG", "135.00", "Large white Kabuli chickpeas"),
            item("Pulses & Legumes", "Masoor Dal (Red Split Lentil)", "PUL_MASOOR_RED_SPLIT", "KG", "90.00", "Split red masoor lentil"),
            item("Pulses & Legumes", "Masoor Whole (Black Lentil)", "PUL_MASOOR_BLACK_WHOLE", "KG", "85.00", "Whole brown masoor lentil"),
            item("Pulses & Legumes", "Rajma (Chitra Spotted)", "PUL_RAJMA_CHITRA", "KG", "140.00", "Spotted Chitra kidney beans"),
            item("Pulses & Legumes", "Rajma (Red Jammu)", "PUL_RAJMA_RED", "KG", "155.00", "Premium red Jammu rajma"),
            item("Pulses & Legumes", "Cowpea / Lobia (White)", "PUL_LOBIA_WHITE", "KG", "95.00", "White black-eyed lobia beans"),
            item("Pulses & Legumes", "Cowpea / Lobia (Red)", "PUL_LOBIA_RED", "KG", "90.00", "Red lobia cowpea beans"),
            item("Pulses & Legumes", "Soyabean (Yellow Whole)", "PUL_SOYABEAN_WHOLE", "KG", "65.00", "High protein yellow soyabean"),
            item("Pulses & Legumes", "Soyabean Chunks", "PUL_SOYA_CHUNKS", "KG", "110.00", "Textured soya protein chunks"),
            item("Pulses & Legumes", "Green Peas (Dry Matar)", "PUL_GREEN_PEAS_DRY", "KG", "70.00", "Dry green peas for cooking"),
            item("Pulses & Legumes", "White Peas (Dry Safed Matar)", "PUL_WHITE_PEAS_DRY", "KG", "65.00", "Dry white peas for ragda"),
            item("Pulses & Legumes", "Horse Gram (Kollu / Gahat)", "PUL_HORSE_GRAM", "KG", "80.00", "Protein-rich horse gram kollu"),
            item("Pulses & Legumes", "Moth Beans (Matki Whole)", "PUL_MOTH_BEANS", "KG", "115.00", "Whole brown moth matki beans"),
            item("Pulses & Legumes", "Broad Beans (Bakla)", "PUL_BROAD_BEANS", "KG", "75.00", "Dried broad fava beans"),
            item("Pulses & Legumes", "Fried Gram (Pottukadalai)", "PUL_FRIED_GRAM", "KG", "125.00", "Roasted split chana for chutney"),
            item("Pulses & Legumes", "Besan (Bengal Gram Flour)", "PUL_BESAN", "KG", "95.00", "Pure fine chana dal besan flour"),
            item("Pulses & Legumes", "Groundnut Kernel (Bold)", "PUL_GROUNDNUT_BOLD", "KG", "130.00", "Raw bold peanut kernels"),
            item("Pulses & Legumes", "Groundnut Kernel (Java)", "PUL_GROUNDNUT_JAVA", "KG", "140.00", "Sweet pink Java peanut kernels"),
            item("Pulses & Legumes", "Roasted Salted Peanuts", "PUL_PEANUTS_ROASTED", "KG", "160.00", "Crispy roasted salted peanuts"),
            item("Pulses & Legumes", "Field Peas (Desi Matar)", "PUL_FIELD_PEAS", "KG", "60.00", "Local field peas"),
            item("Pulses & Legumes", "Val Dal (Field Bean Split)", "PUL_VAL_DAL", "KG", "105.00", "Split field bean val dal"),
            item("Pulses & Legumes", "White Beans (Navy Beans)", "PUL_NAVY_BEANS", "KG", "120.00", "Dried white navy beans"),
            item("Pulses & Legumes", "Lima Beans (Double Beans)", "PUL_LIMA_BEANS", "KG", "150.00", "Large double lima beans"),
            item("Pulses & Legumes", "Soyabean Flour", "PUL_SOYA_FLOUR", "KG", "80.00", "High protein soyabean flour"),
            item("Pulses & Legumes", "Sprouted Moong Mix", "PUL_MOONG_SPROUT", "KG", "120.00", "Fresh sprouted green moong"),
            item("Pulses & Legumes", "Sprouted Kala Chana", "PUL_CHANA_SPROUT", "KG", "90.00", "Fresh sprouted brown chana"),
            item("Pulses & Legumes", "Mix Panchratna Dal", "PUL_MIX_PANCHRATNA", "KG", "145.00", "5-pulse mixed lentil dal"),
            item("Pulses & Legumes", "Organic Tur Dal", "PUL_TUR_ORGANIC", "KG", "180.00", "Certified organic tur dal"),
            item("Pulses & Legumes", "Organic Moong Dal", "PUL_MOONG_ORGANIC", "KG", "140.00", "Certified organic yellow moong"),
            item("Pulses & Legumes", "Organic Chana Dal", "PUL_CHANA_ORGANIC", "KG", "110.00", "Certified organic chana dal"),

            // ==========================================
            // CATEGORY 5: SPICES & CONDIMENTS (40 Commodities)
            // ==========================================
            item("Spices & Condiments", "Red Chilli (Guntur Whole)", "SPI_CHILLI_GUNTUR", "KG", "220.00", "Spicy Guntur red chilli with stem"),
            item("Spices & Condiments", "Red Chilli (Byadgi Mild Red)", "SPI_CHILLI_BYADGI", "KG", "320.00", "Deep red color Byadgi chilli"),
            item("Spices & Condiments", "Red Chilli Powder", "SPI_CHILLI_POWDER", "KG", "260.00", "Pure red chilli powder"),
            item("Spices & Condiments", "Turmeric (Erode Whole Finger)", "SPI_TURMERIC_ERODE", "KG", "160.00", "High curcumin Erode turmeric fingers"),
            item("Spices & Condiments", "Turmeric Powder", "SPI_TURMERIC_POWDER", "KG", "190.00", "Pure ground turmeric powder"),
            item("Spices & Condiments", "Black Pepper (Malabar Garbled)", "SPI_BLACK_PEPPER", "KG", "650.00", "Premium Malabar black pepper bold"),
            item("Spices & Condiments", "White Pepper (Whole)", "SPI_WHITE_PEPPER", "KG", "850.00", "Clean whole white pepper corns"),
            item("Spices & Condiments", "Green Cardamom (8mm Bold)", "SPI_CARDAMOM_GREEN", "KG", "240.00", "Grade A 8mm green cardamom pods"),
            item("Spices & Condiments", "Black Cardamom (Badi Elaichi)", "SPI_CARDAMOM_BLACK", "KG", "120.00", "Aromatic smoky black cardamom"),
            item("Spices & Condiments", "Cumin Seeds (Jeera Bold)", "SPI_CUMIN_JEERA", "KG", "340.00", "Clean bold cumin seeds"),
            item("Spices & Condiments", "Cumin Powder (Jeera Powder)", "SPI_CUMIN_POWDER", "KG", "380.00", "Freshly roasted cumin powder"),
            item("Spices & Condiments", "Coriander Seeds (Whole Dhaniya)", "SPI_CORIANDER_SEEDS", "KG", "130.00", "Aromatic green coriander seeds"),
            item("Spices & Condiments", "Coriander Powder (Dhaniya)", "SPI_CORIANDER_POWDER", "KG", "160.00", "Pure ground coriander powder"),
            item("Spices & Condiments", "Mustard Seeds (Black Rai)", "SPI_MUSTARD_BLACK", "KG", "90.00", "Small pungent black mustard seeds"),
            item("Spices & Condiments", "Mustard Seeds (Yellow Sarson)", "SPI_MUSTARD_YELLOW", "KG", "110.00", "Yellow mustard seeds"),
            item("Spices & Condiments", "Fennel Seeds (Saunf Lucknowi)", "SPI_FENNEL_SAUNF", "KG", "210.00", "Sweet green Lucknowi fennel saunf"),
            item("Spices & Condiments", "Fenugreek Seeds (Methi Dana)", "SPI_FENUGREEK_METHI", "KG", "95.00", "Whole yellow fenugreek seeds"),
            item("Spices & Condiments", "Dry Ginger (Sonth Whole)", "SPI_GINGER_DRY", "KG", "320.00", "Clean sun-dried ginger root"),
            item("Spices & Condiments", "Tamarind (With Seed Block)", "SPI_TAMARIND_SEED", "KG", "90.00", "Natural tamarind with seed"),
            item("Spices & Condiments", "Tamarind (Seedless Block)", "SPI_TAMARIND_SEEDLESS", "KG", "140.00", "Clean seedless tamarind slab"),
            item("Spices & Condiments", "Clove (Laung Madagascar)", "SPI_CLOVE_LAUNG", "KG", "920.00", "Bold Madagascar cloves"),
            item("Spices & Condiments", "Cinnamon Sticks (Dalchini)", "SPI_CINNAMON", "KG", "380.00", "Sweet bark cinnamon sticks"),
            item("Spices & Condiments", "Nutmeg (Jaiphal Whole)", "SPI_NUTMEG", "KG", "750.00", "Whole nutmeg jaiphal nuts"),
            item("Spices & Condiments", "Mace (Javitri)", "SPI_MACE_JAVITRI", "KG", "1800.00", "Aromatic orange mace flower"),
            item("Spices & Condiments", "Star Anise (Chakra Phool)", "SPI_STAR_ANISE", "KG", "820.00", "Whole star anise flowers"),
            item("Spices & Condiments", "Asafoetida (Hing Powder)", "SPI_ASAFOETIDA", "KG", "1400.00", "Compounded Asafoetida hing powder"),
            item("Spices & Condiments", "Poppy Seeds (Khas Khas)", "SPI_POPPY_SEEDS", "KG", "1450.00", "White poppy seeds khas khas"),
            item("Spices & Condiments", "Carom Seeds (Ajwain)", "SPI_CAROM_AJWAIN", "KG", "240.00", "Pungent carom seeds ajwain"),
            item("Spices & Condiments", "Nigella Seeds (Kalonji)", "SPI_NIGELLA_KALONJI", "KG", "280.00", "Black onion seeds kalonji"),
            item("Spices & Condiments", "Bay Leaf (Tejpatta)", "SPI_BAY_LEAF", "KG", "120.00", "Dried Indian bay leaves"),
            item("Spices & Condiments", "Saffron (Kashmiri Mongra)", "SPI_SAFFRON", "GRAM", "350.00", "Pure Kashmiri red saffron strands"),
            item("Spices & Condiments", "Dry Mango Powder (Amchur)", "SPI_AMCHUR", "KG", "220.00", "Tangy green dry mango powder"),
            item("Spices & Condiments", "Garam Masala (Whole Spice Mix)", "SPI_GARAM_MASALA", "KG", "450.00", "Blended Indian whole garam masala"),
            item("Spices & Condiments", "Curry Powder (Madras Style)", "SPI_CURRY_POWDER", "KG", "280.00", "Madras curry spice blend"),
            item("Spices & Condiments", "Black Salt (Kala Namak)", "SPI_BLACK_SALT", "KG", "50.00", "Mineral rich black salt rock"),
            item("Spices & Condiments", "Rock Salt (Sendha Namak)", "SPI_ROCK_SALT", "KG", "60.00", "Pure pink Himalayan rock salt"),
            item("Spices & Condiments", "Iodized Table Salt", "SPI_TABLE_SALT", "KG", "28.00", "Refined vacuum evaporated iodized salt"),
            item("Spices & Condiments", "Kokum (Dried Garcinia)", "SPI_KOKUM", "KG", "260.00", "Dried dark purple kokum rind"),
            item("Spices & Condiments", "Dry Curry Leaves Powder", "SPI_CURRY_LEAVES_POWDER", "KG", "180.00", "Aromatic dried curry leaves powder"),
            item("Spices & Condiments", "Kashmiri Chilli Powder", "SPI_KASHMIRI_CHILLI", "KG", "340.00", "Mild bright red Kashmiri powder"),

            // ==========================================
            // CATEGORY 6: OILSEEDS & OILS (40 Commodities)
            // ==========================================
            item("Oilseeds & Oils", "Mustard Oil (Kachi Ghani)", "OIL_MUSTARD_KACHI_GHANI", "LITER", "145.00", "Cold pressed Kachi Ghani mustard oil"),
            item("Oilseeds & Oils", "Refined Sunflower Oil", "OIL_SUNFLOWER_REFINED", "LITER", "125.00", "Light refined sunflower cooking oil"),
            item("Oilseeds & Oils", "Groundnut Oil (Filtered)", "OIL_GROUNDNUT_FILTERED", "LITER", "175.00", "Pure filtered peanut groundnut oil"),
            item("Oilseeds & Oils", "Sesame / Gingelly Oil (Til)", "OIL_SESAME_GINGELLY", "LITER", "240.00", "Cold pressed sesame gingelly oil"),
            item("Oilseeds & Oils", "Rice Bran Oil (Refined)", "OIL_RICE_BRAN", "LITER", "130.00", "Heart-healthy refined rice bran oil"),
            item("Oilseeds & Oils", "Soybean Refined Oil", "OIL_SOYBEAN_REFINED", "LITER", "120.00", "Clear refined soybean cooking oil"),
            item("Oilseeds & Oils", "Coconut Oil (Pure Cold Pressed)", "OIL_COCONUT_PURE", "LITER", "210.00", "Pure Kerala unrefined coconut oil"),
            item("Oilseeds & Oils", "Palm Oil (RBD Palmolein)", "OIL_PALM_RBD", "LITER", "105.00", "RBD Palmolein vegetable cooking oil"),
            item("Oilseeds & Oils", "Olive Oil (Extra Virgin)", "OIL_OLIVE_EXTRA_VIRGIN", "LITER", "750.00", "Cold pressed extra virgin olive oil"),
            item("Oilseeds & Oils", "Castor Oil (Commercial)", "OIL_CASTOR", "LITER", "160.00", "Industrial & medicinal castor oil"),
            item("Oilseeds & Oils", "Mustard Seeds (Black Seed)", "OILSEED_MUSTARD_BLACK", "KG", "75.00", "Oil extraction black mustard seeds"),
            item("Oilseeds & Oils", "Groundnut Pods (Unshelled)", "OILSEED_GROUNDNUT_PODS", "KG", "85.00", "Raw groundnut peanuts in shell"),
            item("Oilseeds & Oils", "Sesame Seeds (White Til)", "OILSEED_SESAME_WHITE", "KG", "180.00", "Hulled white sesame seeds"),
            item("Oilseeds & Oils", "Sesame Seeds (Black Til)", "OILSEED_SESAME_BLACK", "KG", "195.00", "Un-hulled black sesame seeds"),
            item("Oilseeds & Oils", "Sunflower Seeds (Oil Grade)", "OILSEED_SUNFLOWER", "KG", "65.00", "High oil content sunflower seeds"),
            item("Oilseeds & Oils", "Safflower Seeds (Kardi)", "OILSEED_SAFFLOWER", "KG", "70.00", "Oil grade safflower seeds"),
            item("Oilseeds & Oils", "Castor Seeds", "OILSEED_CASTOR", "KG", "62.00", "Raw castor crop seeds"),
            item("Oilseeds & Oils", "Linseed / Flaxseed (Alsi)", "OILSEED_FLAXSEED_ALSI", "KG", "95.00", "Omega-3 rich flaxseeds alsi"),
            item("Oilseeds & Oils", "Niger Seeds (Ramtil)", "OILSEED_NIGER", "KG", "85.00", "Black niger seeds ramtil"),
            item("Oilseeds & Oils", "Cottonseed (Oil Grade)", "OILSEED_COTTONSEED", "KG", "42.00", "Cottonseed crop for oil extraction"),
            item("Oilseeds & Oils", "Mahua Seeds", "OILSEED_MAHUA", "KG", "48.00", "Wild forest mahua seeds"),
            item("Oilseeds & Oils", "Neem Seeds", "OILSEED_NEEM", "KG", "35.00", "Organic neem seeds for oil"),
            item("Oilseeds & Oils", "Soyabean Crop Seeds", "OILSEED_SOYABEAN", "KG", "52.00", "High protein soyabean seeds"),
            item("Oilseeds & Oils", "Corn Oil (Refined)", "OIL_CORN_REFINED", "LITER", "150.00", "Refined maize corn oil"),
            item("Oilseeds & Oils", "Canola Oil (Imported)", "OIL_CANOLA", "LITER", "180.00", "Pure low erucic acid canola oil"),
            item("Oilseeds & Oils", "Cold Pressed Groundnut Oil", "OIL_GROUNDNUT_COLD_PRESSED", "LITER", "210.00", "Traditional wood pressed peanut oil"),
            item("Oilseeds & Oils", "Cold Pressed Mustard Oil", "OIL_MUSTARD_WOOD_PRESSED", "LITER", "190.00", "Traditional chekku mustard oil"),
            item("Oilseeds & Oils", "Cold Pressed Coconut Oil", "OIL_COCONUT_WOOD_PRESSED", "LITER", "260.00", "Wood pressed virgin coconut oil"),
            item("Oilseeds & Oils", "Blend Cooking Oil", "OIL_BLENDED_VEGETABLE", "LITER", "135.00", "Multi-seed blended vegetable oil"),
            item("Oilseeds & Oils", "Vanaspati Hydrogenated Ghee", "OIL_VANASPATI", "KG", "115.00", "Vegetable vanaspati cooking fat"),
            item("Oilseeds & Oils", "Margarin Vegetable Butter", "OIL_MARGARINE", "KG", "130.00", "Non-dairy vegetable margarine"),
            item("Oilseeds & Oils", "Organic Sesame Oil", "OIL_SESAME_ORGANIC", "LITER", "290.00", "Organic wood pressed til oil"),
            item("Oilseeds & Oils", "Organic Mustard Oil", "OIL_MUSTARD_ORGANIC", "LITER", "220.00", "Organic Kachi Ghani mustard oil"),
            item("Oilseeds & Oils", "Almond Oil (Pure Cold Pressed)", "OIL_ALMOND_PURE", "LITER", "1200.00", "100% pure sweet almond oil"),
            item("Oilseeds & Oils", "Walnut Oil", "OIL_WALNUT", "LITER", "1500.00", "Cold pressed walnut oil"),
            item("Oilseeds & Oils", "Cashew Nut Oil", "OIL_CASHEW", "LITER", "950.00", "Pure cashew nut oil"),
            item("Oilseeds & Oils", "Pumpkin Seed Oil", "OIL_PUMPKIN_SEED", "LITER", "850.00", "Cold pressed pumpkin seed oil"),
            item("Oilseeds & Oils", "Black Seed Oil (Kalonji Oil)", "OIL_BLACK_SEED", "LITER", "1100.00", "Pure Nigella sativa black seed oil"),
            item("Oilseeds & Oils", "Wheat Germ Oil", "OIL_WHEAT_GERM", "LITER", "1600.00", "Vitamin E rich wheat germ oil"),
            item("Oilseeds & Oils", "Grape Seed Oil", "OIL_GRAPE_SEED", "LITER", "900.00", "Refined grape seed cooking oil"),

            // ==========================================
            // CATEGORY 7: DAIRY & POULTRY (40 Commodities)
            // ==========================================
            item("Dairy & Poultry", "Milk (Pasteurized Toned 3% Fat)", "DAI_MILK_TONED", "LITER", "54.00", "Standard pasteurized toned milk"),
            item("Dairy & Poultry", "Milk (Full Cream 6% Fat)", "DAI_MILK_FULL_CREAM", "LITER", "66.00", "Rich full cream pasteurized milk"),
            item("Dairy & Poultry", "Milk (Fresh Cow Milk)", "DAI_MILK_COW", "LITER", "58.00", "Pure farm fresh cow milk"),
            item("Dairy & Poultry", "Milk (Fresh Buffalo Milk)", "DAI_MILK_BUFFALO", "LITER", "70.00", "High fat fresh buffalo milk"),
            item("Dairy & Poultry", "Fresh Curd / Dahi", "DAI_CURD_DAHI", "KG", "65.00", "Thick set pasteurized curd"),
            item("Dairy & Poultry", "Paneer (Fresh Cottage Cheese)", "DAI_PANEER_FRESH", "KG", "360.00", "Soft fresh dairy paneer"),
            item("Dairy & Poultry", "Butter (Salted Yellow)", "DAI_BUTTER_SALTED", "KG", "520.00", "Pasteurized salted creamery butter"),
            item("Dairy & Poultry", "Butter (Unsalted White)", "DAI_BUTTER_UNSALTED", "KG", "540.00", "Fresh unsalted white butter"),
            item("Dairy & Poultry", "Pure Cow Ghee", "DAI_GHEE_COW", "KG", "620.00", "Aromatic pure cow ghee"),
            item("Dairy & Poultry", "Pure Buffalo Ghee", "DAI_GHEE_BUFFALO", "KG", "580.00", "Traditional rich buffalo ghee"),
            item("Dairy & Poultry", "Farm Eggs (Tray 30 Eggs)", "DAI_EGGS_TRAY_30", "DOZEN", "72.00", "Standard farm poultry white eggs"),
            item("Dairy & Poultry", "Organic Brown Eggs", "DAI_EGGS_BROWN", "DOZEN", "110.00", "Free range organic brown eggs"),
            item("Dairy & Poultry", "Quail Eggs (Pack of 12)", "DAI_EGGS_QUAIL", "DOZEN", "60.00", "Nutritious small quail eggs"),
            item("Dairy & Poultry", "Natural Honey (Multiflora)", "DAI_HONEY_NATURAL", "KG", "380.00", "Pure unpasteurized multiflora honey"),
            item("Dairy & Poultry", "Jaggery (Gur Solid Blocks)", "DAI_JAGGERY_GUR", "KG", "55.00", "Traditional cane jaggery gur blocks"),
            item("Dairy & Poultry", "Jaggery Powder (Shakkar)", "DAI_JAGGERY_POWDER", "KG", "65.00", "Organic cane jaggery powder"),
            item("Dairy & Poultry", "Refined White Sugar (M-30)", "DAI_SUGAR_REFINED", "KG", "42.00", "Refined white crystal sugar"),
            item("Dairy & Poultry", "Khandsari Sugar (Unrefined)", "DAI_SUGAR_KHANDSARI", "KG", "58.00", "Traditional unrefined khandsari sugar"),
            item("Dairy & Poultry", "Tea (Assam CTC Leaf)", "DAI_TEA_ASSAM_CTC", "KG", "280.00", "Strong Assam CTC black tea"),
            item("Dairy & Poultry", "Tea (Darjeeling Green Tea)", "DAI_TEA_GREEN", "KG", "650.00", "Organic Darjeeling green tea leaves"),
            item("Dairy & Poultry", "Coffee Beans (Arabica Plantation A)", "DAI_COFFEE_BEANS", "KG", "480.00", "Roasted Arabica coffee beans"),
            item("Dairy & Poultry", "Coffee Powder (Chicory Blend)", "DAI_COFFEE_POWDER", "KG", "360.00", "South Indian filter coffee blend"),
            item("Dairy & Poultry", "Arecanut / Betel Nut (Supari)", "DAI_ARECANUT_SUPARI", "KG", "450.00", "Whole processed betel nut supari"),
            item("Dairy & Poultry", "Betel Leaves (Paan Leaf)", "DAI_BETEL_LEAF", "PIECE", "2.00", "Fresh green betel paan leaves"),
            item("Dairy & Poultry", "Raw Sugarcane", "DAI_SUGARCANE", "KG", "15.00", "Fresh sweet juice sugarcane"),
            item("Dairy & Poultry", "Raw Cotton (Kapas Lint)", "DAI_COTTON_KAPAS", "KG", "75.00", "Un-ginned raw cotton lint"),
            item("Dairy & Poultry", "Cashew Nut (W320 Whole)", "DAI_CASHEW_W320", "KG", "850.00", "Grade W320 premium whole cashews"),
            item("Dairy & Poultry", "Almonds (California Badam)", "DAI_ALMOND_CALIFORNIA", "KG", "680.00", "Sweet California whole almonds"),
            item("Dairy & Poultry", "Walnuts (Kashmiri Giri)", "DAI_WALNUT_KASHMIRI", "KG", "950.00", "Whole Kashmiri walnut kernels"),
            item("Dairy & Poultry", "Raisins (Malay Green Kishmish)", "DAI_RAISINS_GREEN", "KG", "240.00", "Sweet green seedless raisins"),
            item("Dairy & Poultry", "Pistachios (Roasted Salted)", "DAI_PISTACHIO_ROASTED", "KG", "1100.00", "Salted roasted pistachio nuts"),
            item("Dairy & Poultry", "Dried Dates (Chuara)", "DAI_DATES_DRIED", "KG", "280.00", "Hard dried yellow chuara dates"),
            item("Dairy & Poultry", "Condensed Milk", "DAI_CONDENSED_MILK", "KG", "220.00", "Sweetened condensed milk tin"),
            item("Dairy & Poultry", "Milk Powder (Skimmed)", "DAI_MILK_POWDER", "KG", "320.00", "Instant skimmed milk powder"),
            item("Dairy & Poultry", "Cheese Slices (Cheddar)", "DAI_CHEESE_SLICES", "KG", "480.00", "Processed cheddar cheese slices"),
            item("Dairy & Poultry", "Mozzarella Cheese (Shredded)", "DAI_MOZZARELLA", "KG", "550.00", "Pure milk mozzarella cheese"),
            item("Dairy & Poultry", "Buttermilk (Chaas)", "DAI_BUTTERMILK_CHAAS", "LITER", "30.00", "Spiced refreshing dahi chaas"),
            item("Dairy & Poultry", "Flavored Milk (Chocolate)", "DAI_FLAVORED_MILK", "LITER", "80.00", "Sterilized chocolate flavored milk"),
            item("Dairy & Poultry", "Organic Desi Cow Ghee (A2)", "DAI_GHEE_A2", "KG", "1400.00", "Traditional bilona A2 desi cow ghee"),
            item("Dairy & Poultry", "Wild Forest Honey", "DAI_HONEY_WILD", "KG", "550.00", "Raw unprocessed wild forest honey")
        );
    }

    private static CommoditySeedItem item(String category, String name, String code, String unit, String price, String desc) {
        return new CommoditySeedItem(category, name, code, unit, new BigDecimal(price), desc);
    }
}
